### ISSUE TITLE
Problems with request to inference appservice

### ISSUE THREAD

**Issue by Adapter668** [microsoft/InnerEye-Gateway#103] opened 2022-06-29 07:42 UTC
Hi, I'm trying to manually test the gateway (with those instructions https://github.com/microsoft/InnerEye-Gateway#to-manually-test-the-gateway).
In the gateway processor, there is sending a request to inference AppService, and it supposes to send with the POST method
![2022-06-29 09_27_41-Microsoft Gateway(debugowanie) - Microsoft Visual Studio(Administrator)](https://user-images.githubusercontent.com/12545796/176377714-8d77ddb7-9687-4d38-b5bc-e26f1b2983ad.png)

But I got the status code MethodNotAllowed and in logs of inference AppService I have this output:
![image](https://user-images.githubusercontent.com/12545796/176378402-db3e553a-fd9a-42dc-9b25-343af6aad3b3.png)

Should I configure it somewhere or do something else?
The inference AppService is working fine when I'm sending requests from Postman.

**Comment by peterhessey** [comment] 2022-06-29 11:55
Do you get a 200 response when running the command `curl -i -H "API_AUTH_SECRET: <val of CUSTOMCONNSTR_API_AUTH_SECRET>" https://<INFERENCESERVICENAME>/v1/ping?

**Comment by peterhessey** [comment] 2022-06-29 12:38
Hm very weird. I haven't done manual testing on the Gateway myself yet unfortunately so can't help quite yet. I'm away this from tomorrow til Monday but will look into this in more detail first thing once I am back at work. Will post any outcomes here!

**Comment by Adapter668** [comment] 2022-06-29 12:41
Thank you, I'll also post here if I think of some solution

**Comment by Adapter668** [comment] 2022-07-05 06:29
I couldn't solve the problem. I hope you can help me with this one

**Comment by ant0nsc** [comment] 2022-07-05 10:13
@Adapter668 , @javier-alvarez spotted that there is an odd discrepancy between the screenshot that you shared about the request, and the error message: The request shows as a `POST` request, but the error message says it is a `GET` request. Clearly the call to start a model does not have a `GET` counterpart, maybe that's where the error `MethodNotAllowed` comes from? I'm really puzzled though about which instance could transform the `POST` request into a `GET` request?

**Comment by Adapter668** [comment] 2022-07-06 07:30
That's my question exactly. I thought it was weird, that request created with `POST` method was suddenly changed to `GET` request. 
I set up the gateway according to instructions in README.md and this error happened.
Maybe if you couldn't replicate the error and help me here, we can schedule a call to try to resolve this issue?

**Comment by peterhessey** [comment] 2022-07-07 08:19
A call sounds good, feel free to e-mail me at a-phessey@microsoft.com and let me know your availability for tomorrow/next week!

**Comment by peterhessey** [comment] 2022-07-08 08:50
So I've been playing around with this yesterday and this morning and can't seem to repeat your error - manual tests all seem to work fine for me! @Adapter668 if you get a chance before our call (and haven't already tried this), try redeploying a completely fresh inference service using the latest code and testing against that again and see if that makes any difference

**Comment by Adapter668** [comment] 2022-07-08 10:28
I've just tried this with the latest code from inference and gateway and I still have the same problem. I've probably done something wrong with the configuration of the gateway or those manual tests, so hopefully, the call will clarify where is the problem

**Comment by Adapter668** [comment] 2022-07-13 07:45
Hi, I'm not sure if you were still looking into my issue, because I've checked again (built everything from scratch, making sure everything is built on my computer and turned off the VPN) and it's still the same. So maybe you have some new ideas on that

**Comment by ant0nsc** [comment] 2022-07-14 08:10
I spoke with @peterhessey about the problem yesterday, and he says that he is still unable to reproduce the problem. It seems to be specific to your networking setup? Have you consulted with your internal IT folks?

**Comment by Adapter668** [comment] 2022-07-25 11:41
So I've checked the problem with the IT guys and also checked on a different computer. And  I could run it on Windows 10 and the problem occurs on Windows 11.

**Comment by ant0nsc** [comment] 2022-07-26 20:51
@Adapter668 , That's really odd... the problem is only on Windows 11, but not on Windows 10? 
All our machines are Windows 11, too, and we have not been able to reproduce.

**Comment by peterhessey** [comment] 2022-07-27 07:47
@ant0nsc my machine is running windows 10 - not sure if anyone other than myself has tried to reproduce this error recently?

**Comment by ant0nsc** [comment] 2022-07-27 09:56
@peterhessey Ooops, my bad, I thought you're on Windows 11 too! Let's chat later.

**Comment by peterhessey** [comment] 2022-11-16 10:25
@Adapter668 is this still an issue for you? I've been running this on windows 11 myself without any problems

**Comment by peterhessey** [comment] 2022-11-28 08:58
Closing due to lack of info + repeatability

**Closed by peterhessey** 2022-11-28 08:58 UTC

**Comment by Adapter668** [comment] 2022-11-28 09:11
Sorry, I was on vacation when you wrote the last comment. I didn't have time to check if it now works on windows 11, but hope it will

**Comment by peterhessey** [comment] 2022-11-28 11:30
No worries at all! Can always re-open this issue if it's still a problem in the future :)
